<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>field_login</name>
   <tag></tag>
   <elementGuidId>a14312f5-2aba-4140-bf99-7361781af18d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id=&quot;${field}&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id=&quot;${field}&quot;]</value>
      <webElementGuid>2ca3ffb6-08d7-4b48-bd48-7beef41cc219</webElementGuid>
   </webElementProperties>
</WebElementEntity>
