<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>form_title</name>
   <tag></tag>
   <elementGuidId>2ee133d0-7d29-44db-bc1c-997eb2e89c25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div/div/div/div/div/div/div[1]/div/div/div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div/div/div/div/div/div/div[1]/div/div/div[1]</value>
      <webElementGuid>4d7fdd1d-51d4-4568-89de-5e7deb2251c5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
