<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>field_team_review</name>
   <tag></tag>
   <elementGuidId>186c10f8-59ec-4c36-b72a-8b6d1e3dcb03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//form[@id=&quot;formValidate&quot;]/div[1]/div[7]/div[1]/div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//form[@id=&quot;formValidate&quot;]/div[1]/div[7]/div[1]/div[1]</value>
      <webElementGuid>134af1b3-00a7-4a5e-b54e-a2368d042843</webElementGuid>
   </webElementProperties>
</WebElementEntity>
