<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_nonruntin</name>
   <tag></tag>
   <elementGuidId>6f608f96-6bfb-4e85-b01b-122d6ca792be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id=&quot;flex2&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id=&quot;flex2&quot;]</value>
      <webElementGuid>31f85862-9579-4d94-ba31-d521f92c08f4</webElementGuid>
   </webElementProperties>
</WebElementEntity>
